# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 06:47
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import payroll.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(
                    max_length=10, verbose_name='Department Code')),
                ('name', models.CharField(
                    max_length=256, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10,
                                          verbose_name='Designation Code')),
                ('title', models.CharField(max_length=256, verbose_name='Job Title')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[
                 ('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[
                 ('MR', 'MARRIED'), ('S', 'SINGLE')], default='S', max_length=2)),
                ('address_1', models.CharField(blank=True, max_length=256)),
                ('address_2', models.CharField(blank=True, max_length=256)),
                ('country', django_countries.fields.CountryField(
                    blank=True, max_length=2)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(
                    blank=True, max_length=128)),
                ('alternate_phone', phonenumber_field.modelfields.PhoneNumberField(
                    blank=True, max_length=128)),
                ('qualification', models.CharField(blank=True, max_length=256)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('personal_url', models.URLField(blank=True)),
                ('identity_proof', models.FileField(blank=True,
                                                    upload_to=payroll.models.user_directory_path)),
                ('resume', models.FileField(blank=True,
                                            upload_to=payroll.models.user_directory_path)),
                ('profile_picture', models.ImageField(blank=True,
                                                      upload_to=payroll.models.user_directory_path)),
                ('previous_company_name', models.CharField(
                    blank=True, max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.CASCADE, to='payroll.Department')),
                ('job_title', models.ForeignKey(blank=True, null=True,
                                                on_delete=django.db.models.deletion.CASCADE, to='payroll.Designation')),
            ],
            options={
                'ordering': ['-created_date'],
                'get_latest_by': '-created_date',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=256)),
                ('pan_number', models.CharField(blank=True, max_length=30)),
                ('pf_number', models.CharField(blank=True,
                                               max_length=50, verbose_name='PF Account Number')),
                ('gross_salary', models.DecimalField(
                    decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal(
                    '0.00'), max_digits=8, verbose_name='Basic Salary')),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal(
                    '0.00'), max_digits=8, verbose_name='HRA')),
                ('conveyance', models.DecimalField(blank=True,
                                                   decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('medical', models.DecimalField(blank=True,
                                                decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('flexible_benifits', models.DecimalField(blank=True,
                                                          decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('pf_employee', models.DecimalField(blank=True, decimal_places=2, default=Decimal(
                    '0.00'), max_digits=8, verbose_name='PF from Employee')),
                ('pf_employer', models.DecimalField(blank=True, decimal_places=2, default=Decimal(
                    '0.00'), max_digits=8, verbose_name='PF from Employer')),
                ('income_tax', models.DecimalField(blank=True,
                                                   decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('professional_tax', models.DecimalField(blank=True,
                                                         decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('other_charges', models.DecimalField(blank=True,
                                                      decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, to='payroll.Skill'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_profile',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='leave_tracker.UserProfile'),
        ),
    ]
