# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import payroll.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department Code', models.CharField(max_length=10)),
                ('Department Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation Code', models.CharField(max_length=10)),
                ('Job Title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee ID', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('Date of Birth', models.DateTimeField(blank=True, null=True)),
                ('Marital Status', models.CharField(choices=[('MR', 'MARRIED'), ('S', 'SINGLE')], default='S', max_length=2)),
                ('Address 1', models.CharField(blank=True, max_length=256)),
                ('Address 2', models.CharField(blank=True, max_length=256)),
                ('Country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('Zipcode', models.IntegerField(blank=True, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Alternate Phone', models.IntegerField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=256)),
                ('Experience', models.IntegerField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, upload_to=payroll.models.user_directory_path)),
                ('profile_picture', models.ImageField(blank=True, upload_to=payroll.models.user_directory_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Department')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank Account Number', models.CharField(max_length=256)),
                ('PAN', models.CharField(blank=True, max_length=30)),
                ('PF Account Number', models.CharField(blank=True, max_length=50)),
                ('Gross Salary', models.DecimalField(decimal_places=6, max_digits=6)),
                ('Basic Salary', models.DecimalField(decimal_places=6, max_digits=6)),
                ('HRA', models.DecimalField(decimal_places=6, max_digits=6)),
                ('Conveyance', models.DecimalField(blank=True, decimal_places=6, max_digits=6)),
                ('Medical', models.DecimalField(blank=True, decimal_places=6, max_digits=6)),
                ('Flexible Benifits', models.DecimalField(blank=True, decimal_places=6, max_digits=6)),
                ('PF from Employee', models.DecimalField(blank=True, decimal_places=6, max_digits=6)),
                ('PF from Employer', models.DecimalField(blank=True, decimal_places=6, max_digits=6)),
                ('Income Tax', models.DecimalField(blank=True, decimal_places=6, max_digits=6)),
                ('Professional Tax', models.DecimalField(blank=True, decimal_places=6, max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, to='payroll.Skill'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_tracker.UserProfile'),
        ),
    ]
